# Too Hard / Soft Analysis

In [3]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
import pytz
from datetime import datetime, timedelta
import os
import sys
import io
from io import BytesIO
import csv
import google.auth
from google.cloud import bigquery
#from google.cloud import bigquery_storage

In [5]:
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "./market-analysis-project-91130-9f9a036682b6.json"

credentials, project_id = google.auth.default(
    scopes=["https://www.googleapis.com/auth/cloud-platform"]
)

bqclient = bigquery.Client(credentials=credentials, project=project_id,)
#bqstorageclient = bigquery_storage.BigQueryReadClient(credentials=credentials)

In [6]:
sql = f"""
    select * from mart.amz_us_zinus_crwl_rpa_rvw
    where cf1 is not null
"""

df = bqclient.query(sql).to_dataframe()

In [7]:
df

,sku,category,financial_category,detailed_category,collection,asin,date,yr_month,star,review_id,...,photo,image_links,title,review_text,link,cf1,cf2,cf1_agg,cf2_agg,yr_wk
0,ADB-14F,Frames for Mattresses,Platform Beds,Metal,Jared,B07W69WKW4,2020-10-28,202010,1.0,RS357HGNZ3NHK,...,None,None,This bed sucks,My bed was fine for about 2 weeks. All of a su...,https://www.amazon.com/gp/customer-reviews/RS3...,Durability,None,"Customer service,Durability",Warranty,202044
1,ADB-14F,Frames for Mattresses,Platform Beds,Metal,Jared,B07W69WKW4,2020-10-28,202010,1.0,RS357HGNZ3NHK,...,None,None,This bed sucks,My bed was fine for about 2 weeks. All of a su...,https://www.amazon.com/gp/customer-reviews/RS3...,Customer service,Warranty,"Customer service,Durability",Warranty,202044
2,ADB-14F,Frames for Mattresses,Platform Beds,Metal,Jared,B07W69WKW4,2022-11-20,202211,1.0,R17IZHQYM543L0,...,None,None,Legs fell off,I will never order from yhem again bcuz I don'...,https://www.amazon.com/gp/customer-reviews/R17...,Durability,Broken,"Customer service,Durability","Broken,Unhelpful",202247
3,ADB-14F,Frames for Mattresses,Platform Beds,Metal,Jared,B07W69WKW4,2022-08-19,202208,1.0,R3MOH5XDWDRSGF,...,None,None,warning about this,Warning: Do not order this product it didn't w...,https://www.amazon.com/gp/customer-reviews/R3M...,Defect,None,Defect,,202233
4,ADB-14F,Frames for Mattresses,Platform Beds,Metal,Jared,B07W69WKW4,2022-11-20,202211,1.0,R17IZHQYM543L0,...,None,None,Legs fell off,I will never order from yhem again bcuz I don'...,https://www.amazon.com/gp/customer-reviews/R17...,Customer service,Unhelpful,"Customer service,Durability","Broken,Unhelpful",202247
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42318,ZU-USSMC1-74D,Furniture,Sofa,Sectional,Hudson Sectional,B0BQ33BXKV,2023-01-20,202301,2.0,R37WEVCXIN1A1U,...,None,None,Not as thick as pictures show,"I so wanted to like this couch, but I am retur...",https://www.amazon.com/gp/customer-reviews/R37...,Uncomfortable,None,"Others,Uncomfortable",Too thin,202303
42319,ZU-USSMC1-74D,Furniture,Sofa,Sectional,Hudson Sectional,B0BQ33BXKV,2023-01-20,202301,2.0,R37WEVCXIN1A1U,...,None,None,Not as thick as pictures show,"I so wanted to like this couch, but I am retur...",https://www.amazon.com/gp/customer-reviews/R37...,Others,Too thin,"Others,Uncomfortable",Too thin,202303
42320,ZU-UTOTV2-16B,Furniture,Non Bedroom Furniture,Living Room,Bennett TV Stand,B0BSGLH8HM,2023-07-25,202307,2.0,RRF2KEGDKVMHE,...,Y,https://m.media-amazon.com/images/I/814sYQ9kWx...,Damaged top,"Over halfway finished with assembly, and I dis...",https://www.amazon.com/gp/customer-reviews/RRF...,Shipping damage,None,Shipping damage,,202330
42321,ZU-UTOTV3-16E,Furniture,Non Bedroom Furniture,Living Room,Camden TV Stand,B0BTYJF57J,2025-01-29,202501,2.0,RWFWSZNAL62CP,...,None,None,It's just ok,It's not very sturdy and the top piece broke w...,https://www.amazon.com/gp/customer-reviews/RWF...,Durability,Broken,Durability,Broken,202505
42322,SM-SC-SBBK-14F-FR,SmartBases,SmartBases,SmartBases,Shawn 14in Regular,B006MISZOC,2022-01-20,202201,4.0,R1A17PQPSAANC0,...,None,None,Works well,Works well,https://www.amazon.com/gp/customer-reviews/R1A...,Customer error,Wrong rating,Customer error,Wrong rating,202203

In [ ]:
df

In [8]:
df = pd.read_csv("review-vc_sales_by_collection.csv")

In [9]:
foam_df = df[df['financial_category'] == 'Foam Mattresses']

In [10]:
foam_df = foam_df[foam_df['collection'] == '__TOTAL__']

In [11]:
foam_df.to_csv('foam_df_2_hard_soft.csv')

In [12]:
foam_df

,yr_month,financial_category,collection,written_avg_rating,written_12_cnt,witten_all_cnt,written_12_ratio,all_avg_rating,all_12_cnt,all_all_cnt,all_12_ratio,sales_amount,sales_qty
31,202201,Foam Mattresses,__TOTAL__,3.314070,157.0,398.0,0.394472,NaN,NaN,NaN,NaN,9613915.51,31078.0
449,202202,Foam Mattresses,__TOTAL__,3.188732,144.0,355.0,0.405634,NaN,NaN,NaN,NaN,9623567.78,32832.0
863,202203,Foam Mattresses,__TOTAL__,3.400485,155.0,412.0,0.376214,NaN,NaN,NaN,NaN,14457140.02,55343.0
1279,202204,Foam Mattresses,__TOTAL__,3.474860,118.0,358.0,0.329609,NaN,NaN,NaN,NaN,13125662.33,44857.0
1711,202205,Foam Mattresses,__TOTAL__,3.604317,129.0,417.0,0.309353,4.466096,335.0,4439.0,0.075467,17729307.76,66675.0
2259,202206,Foam Mattresses,__TOTAL__,3.659722,126.0,432.0,0.291667,4.440899,330.0,4137.0,0.079768,18774110.07,74184.0
2820,202207,Foam Mattresses,__TOTAL__,3.779264,154.0,598.0,0.257525,4.486473,417.0,5914.0,0.070511,34890290.71,137528.0
3383,202208,Foam Mattresses,__TOTAL__,3.692192,188.0,666.0,0.282282,4.479640,405.0,5673.0,0.071391,30289768.90,123213.0
3950,202209,Foam Mattresses,__TOTAL__,3.747706,178.0,654.0,0.272171,4.492931,398.0,5871.0,0.067791,22571578.18,96290.0
4520,202210,Foam Mattresses,__TOTAL__,3.522801,195.0,614.0,0.317590,4.422867,399.0,4758.0,0.083859,27758714.89,121388.0
5091,202211,Foam Mattresses,__TOTAL__,3.475200,208.0,625.0,0.332800,4.348451,355.0,3550.0,0.100000,29276615.22,123368.0
5666,202212,Foam Mattresses,__TOTAL__,3.257660,287.0,718.0,0.399721,4.211092,471.0,3444.0,0.136760,24765593.08,115032.0
6246,202301,Foam Mattresses,__TOTAL__,3.522367,217.0,693.0,0.313131,4.338263,384.0,3719.0,0.103254,20414620.93,86700.0
6832,202302,Foam Mattresses,__TOTAL__,3.476923,177.0,520.0,0.340385,4.252709,304.0,2307.0,0.131773,17890538.09,75209.0
7422,202303,Foam Mattresses,__TOTAL__,3.563780,204.0,635.0,0.321260,4.346454,363.0,3328.0,0.109075,22921709.85,99091.0
8015,202304,Foam Mattresses,__TOTAL__,3.472693,176.0,531.0,0.331450,4.334140,311.0,2894.0,0.107464,21317287.28,90768.0
8609,202305,Foam Mattresses,__TOTAL__,3.462656,168.0,482.0,0.348548,4.341860,304.0,2893.0,0.105081,18639972.50,72411.0
9204,202306,Foam Mattresses,__TOTAL__,3.707158,129.0,461.0,0.279826,4.419219,249.0,2841.0,0.087645,17963901.77,77852.0
9800,202307,Foam Mattresses,__TOTAL__,3.631670,175.0,581.0,0.301205,4.325179,285.0,2657.0,0.107264,36659801.73,144338.0
10397,202308,Foam Mattresses,__TOTAL__,3.688468,166.0,581.0,0.285714,4.366549,279.0,2840.0,0.098239,19663272.52,89959.0
10994,202309,Foam Mattresses,__TOTAL__,3.750000,110.0,396.0,0.277778,4.380162,227.0,2349.0,0.096637,13084732.94,55501.0
11592,202310,Foam Mattresses,__TOTAL__,3.620219,112.0,366.0,0.306011,4.331986,244.0,2226.0,0.109614,13766053.60,57584.0
12190,202311,Foam Mattresses,__TOTAL__,3.402332,118.0,343.0,0.344023,4.203741,210.0,1497.0,0.140281,18154875.29,92444.0
12793,202312,Foam Mattresses,__TOTAL__,3.444444,173.0,477.0,0.362683,4.225616,264.0,1866.0,0.141479,20648915.98,111203.0
13413,202401,Foam Mattresses,__TOTAL__,3.507194,176.0,556.0,0.316547,4.215676,272.0,1952.0,0.139344,14079036.10,69853.0
14049,202402,Foam Mattresses,__TOTAL__,3.549261,136.0,406.0,0.334975,4.298140,213.0,1667.0,0.127774,13682453.76,72589.0
14695,202403,Foam Mattresses,__TOTAL__,3.616628,135.0,433.0,0.311778,4.239528,235.0,1695.0,0.138643,18658866.12,91938.0
15343,202404,Foam Mattresses,__TOTAL__,3.558712,169.0,528.0,0.320076,4.238892,259.0,1913.0,0.135389,16939536.69,84082.0
16002,202405,Foam Mattresses,__TOTAL__,3.548729,159.0,472.0,0.336864,4.252288,239.0,1748.0,0.136728,15253339.45,69171.0
16668,202406,Foam Mattresses,__TOTAL__,3.615741,133.0,432.0,0.307870,4.292994,216.0,1727.0,0.125072,15678454.61,74771.0
17336,202407,Foam Mattresses,__TOTAL__,3.644958,144.0,476.0,0.302521,4.350850,224.0,1941.0,0.115404,14856916.12,66140.0
18004,202408,Foam Mattresses,__TOTAL__,3.647982,131.0,446.0,0.293722,4.297551,231.0,1919.0,0.120375,18535813.07,95733.0
18673,202409,Foam Mattresses,__TOTAL__,3.676230,142.0,488.0,0.290984,4.173699,222.0,1422.0,0.156118,18427561.21,96938.0
19350,202410,Foam Mattresses,__TOTAL__,3.534314,130.0,408.0,0.318627,4.141970,180.0,1127.0,0.159716,12283332.58,63473.0
20028,202411,Foam Mattresses,__TOTAL__,3.437158,126.0,366.0,0.344262,3.556373,128.0,408.0,0.313725,16364606.58,94029.0
20706,202412,Foam Mattresses,__TOTAL__,3.233990,164.0,406.0,0.403941,3.233990,164.0,406.0,0.403941,12874164.69,77553.0
21384,202501,Foam Mattresses,__TOTAL__,3.205285,199.0,492.0,0.404472,3.205285,199.0,492.0,0.404472,13152413.23,78200.0
22063,202502,Foam Mattresses,__TOTAL__,3.115566,183.0,424.0,0.431604,4.312362,415.0,3624.0,0.114514,14498791.80,94588.0
22748,202503,Foam Mattresses,__TOTAL__,3.455197,92.0,279.0,0.329749,3.455197,92.0,279.0,0.329749,17986298.94,121584.0

## too hard / soft

In [14]:
df1 = pd.read_csv("review_sales_too_hard_soft.csv")

In [15]:
df1

,Unnamed: 0,yr_month,financial_category,written_avg_rating,written_12_cnt,written_all_cnt,written_12_ratio,all_avg_rating,all_12_cnt,all_all_cnt,all_12_ratio,sales_amount,sales_qty
0,0,202212,SmartBases,4.038674,37,181,0.204420,4.512716,73.0,983.0,0.074262,1729285.82,17377
1,1,202412,Platform Beds,3.854545,103,440,0.234091,3.854545,103.0,440.0,0.234091,4021850.94,40099
2,2,202309,Toppers,3.106061,31,66,0.469697,4.163462,61.0,416.0,0.146635,240646.93,4615
3,3,202201,Non Bedroom Furniture,3.853333,19,75,0.253333,NaN,NaN,NaN,NaN,518281.03,4766
4,4,202411,Others,5.000000,0,2,0.000000,4.833333,0.0,6.0,0.000000,41752.46,1279
...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,385,202303,Toppers,2.700637,89,157,0.566879,3.853425,166.0,730.0,0.227397,1018152.28,20058
386,386,202311,Box Springs,3.840206,49,194,0.252577,4.371156,100.0,943.0,0.106045,4148741.49,31839
387,387,202202,Box Springs,4.133739,56,329,0.170213,NaN,NaN,NaN,NaN,6632445.72,48676
388,388,202401,Toppers,3.041667,21,48,0.437500,4.150602,48.0,332.0,0.144578,185152.78,3537
389,389,202408,Non Bedroom Furniture,4.125000,2,16,0.125000,4.337500,7.0,80.0,0.087500,286310.36,3435

In [16]:
foam_df1 = df1[df1['financial_category'] == 'Foam Mattresses']

In [17]:
foam_df1

,Unnamed: 0,yr_month,financial_category,written_avg_rating,written_12_cnt,written_all_cnt,written_12_ratio,all_avg_rating,all_12_cnt,all_all_cnt,all_12_ratio,sales_amount,sales_qty
8,8,202207,Foam Mattresses,3.779264,154,598,0.257525,4.486473,417.0,5914.0,0.070511,34890290.71,137528
10,10,202310,Foam Mattresses,3.620219,112,366,0.306011,4.331986,244.0,2226.0,0.109614,13766053.60,57584
11,11,202301,Foam Mattresses,3.522367,217,693,0.313131,4.338263,384.0,3719.0,0.103254,20414620.93,86700
18,18,202401,Foam Mattresses,3.507194,176,556,0.316547,4.215676,272.0,1952.0,0.139344,14079036.10,69853
37,37,202502,Foam Mattresses,3.118203,182,423,0.430260,4.313000,414.0,3623.0,0.114270,14498791.80,94588
41,41,202203,Foam Mattresses,3.400485,155,412,0.376214,NaN,NaN,NaN,NaN,14457140.02,55343
44,44,202501,Foam Mattresses,3.205285,199,492,0.404472,3.205285,199.0,492.0,0.404472,13152413.23,78200
51,51,202409,Foam Mattresses,3.676230,142,488,0.290984,4.173699,222.0,1422.0,0.156118,18427561.21,96938
59,59,202302,Foam Mattresses,3.476923,177,520,0.340385,4.252709,304.0,2307.0,0.131773,17890538.09,75209
88,88,202307,Foam Mattresses,3.631670,175,581,0.301205,4.325179,285.0,2657.0,0.107264,36659801.73,144338
102,102,202212,Foam Mattresses,3.257660,287,718,0.399721,4.211092,471.0,3444.0,0.136760,24765593.08,115032
112,112,202403,Foam Mattresses,3.616628,135,433,0.311778,4.239528,235.0,1695.0,0.138643,18658866.12,91938
126,126,202402,Foam Mattresses,3.549261,136,406,0.334975,4.298140,213.0,1667.0,0.127774,13682453.76,72589
130,130,202404,Foam Mattresses,3.558712,169,528,0.320076,4.238892,259.0,1913.0,0.135389,16939536.69,84082
152,152,202503,Foam Mattresses,3.487500,26,80,0.325000,3.487500,26.0,80.0,0.325000,17850319.53,120054
175,175,202411,Foam Mattresses,3.437158,126,366,0.344262,3.556373,128.0,408.0,0.313725,16364606.58,94029
180,180,202204,Foam Mattresses,3.474860,118,358,0.329609,NaN,NaN,NaN,NaN,13125662.33,44857
183,183,202208,Foam Mattresses,3.692192,188,666,0.282282,4.479640,405.0,5673.0,0.071391,30289768.90,123213
205,205,202408,Foam Mattresses,3.647982,131,446,0.293722,4.297551,231.0,1919.0,0.120375,18535813.07,95733
228,228,202210,Foam Mattresses,3.522801,195,614,0.317590,4.422867,399.0,4758.0,0.083859,27758714.89,121388
231,231,202309,Foam Mattresses,3.750000,110,396,0.277778,4.380162,227.0,2349.0,0.096637,13084732.94,55501
232,232,202407,Foam Mattresses,3.644958,144,476,0.302521,4.350850,224.0,1941.0,0.115404,14856916.12,66140
233,233,202303,Foam Mattresses,3.563780,204,635,0.321260,4.346454,363.0,3328.0,0.109075,22921709.85,99091
250,250,202410,Foam Mattresses,3.534314,130,408,0.318627,4.141970,180.0,1127.0,0.159716,12283332.58,63473
251,251,202305,Foam Mattresses,3.462656,168,482,0.348548,4.341860,304.0,2893.0,0.105081,18639972.50,72411
270,270,202206,Foam Mattresses,3.659722,126,432,0.291667,4.440899,330.0,4137.0,0.079768,18774110.07,74184
281,281,202209,Foam Mattresses,3.747706,178,654,0.272171,4.492931,398.0,5871.0,0.067791,22571578.18,96290
291,291,202311,Foam Mattresses,3.402332,118,343,0.344023,4.203741,210.0,1497.0,0.140281,18154875.29,92444
292,292,202405,Foam Mattresses,3.548729,159,472,0.336864,4.252288,239.0,1748.0,0.136728,15253339.45,69171
296,296,202308,Foam Mattresses,3.688468,166,581,0.285714,4.366549,279.0,2840.0,0.098239,19663272.52,89959
304,304,202201,Foam Mattresses,3.314070,157,398,0.394472,NaN,NaN,NaN,NaN,9613915.51,31078
305,305,202412,Foam Mattresses,3.233990,164,406,0.403941,3.233990,164.0,406.0,0.403941,12874164.69,77553
318,318,202312,Foam Mattresses,3.444444,173,477,0.362683,4.225616,264.0,1866.0,0.141479,20648915.98,111203
335,335,202304,Foam Mattresses,3.472693,176,531,0.331450,4.334140,311.0,2894.0,0.107464,21317287.28,90768
346,346,202406,Foam Mattresses,3.615741,133,432,0.307870,4.292994,216.0,1727.0,0.125072,15678454.61,74771
347,347,202211,Foam Mattresses,3.475200,208,625,0.332800,4.348451,355.0,3550.0,0.100000,29276615.22,123368
350,350,202205,Foam Mattresses,3.604317,129,417,0.309353,4.466096,335.0,4439.0,0.075467,17729307.76,66675
375,375,202202,Foam Mattresses,3.188732,144,355,0.405634,NaN,NaN,NaN,NaN,9623567.78,32832
376,376,202306,Foam Mattresses,3.707158,129,461,0.279826,4.419219,249.0,2841.0,0.087645,17963901.77,77852