# 년도별 Adjusted Rating 계산

In [96]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [106]:
df = pd.read_csv('collection_yearly_out1_rating_sales_2_4.csv')

In [108]:
df_2022 = df[['collection','2022_rating','2022_sales']].copy()

In [110]:
df_2022['2022_weight'] = df_2022['2022_rating'] * df_2022['2022_sales']

In [112]:
df_2022

                  collection  2022_rating  2022_sales  2022_weight
0     12in MyGel w WonderBox          0.0        0.00          0.0
1      12in GTMF w WonderBox          0.0        0.00          0.0
2     10in MyGel w WonderBox          0.0        0.00          0.0
3      10in GTMF w WonderBox          0.0        0.00          0.0
4       6in GTMF w WonderBox          0.0        0.00          0.0
..                       ...          ...         ...          ...
664        Wesley Side Table          0.0      798.18          0.0
665    William Trestle Table          0.0      533.33          0.0
666         WonderBox Kellen          0.0        0.00          0.0
667  Wood Squre Dining Table          0.0        0.00          0.0
668   Zaalonge Console Table          0.0        0.00          0.0

[669 rows x 4 columns]

In [114]:
total_weight_2022 = df_2022['2022_weight'].sum()
df_2022['2022_contribution'] = df_2022['2022_weight'] / total_weight_2022*100
#df_2022['2022_contribution'] = df_2022['2022_contribution'].round(4)

In [116]:
df_2022['2022_contribution'].sum()

100.00000000000001

In [122]:
df_2022 = df_2022.sort_values(by='2022_contribution', ascending=False)
df_2022['2022_acc_contribution'] = df_2022['2022_contribution'].cumsum()

In [ ]:
df_2022

In [130]:
top_80 = df_2022[df_2022['2022_acc_contribution'] <= 80]

In [132]:
top_80

,collection,2022_rating,2022_sales,2022_weight,2022_contribution,2022_acc_contribution
244,12in Green Tea MF,3.277842,71351952.08,2.338804e+08,9.179879,9.179879
57,Armita 9in,3.962261,27701764.81,1.097616e+08,4.308177,13.488056
242,12in Gel Green Tea MF,3.502406,20061084.38,7.026206e+07,2.757807,16.245863
213,10in Green Tea MF,3.516445,19934950.76,7.010015e+07,2.751452,18.997315
229,6in Green Tea MF,3.462912,19159651.82,6.634818e+07,2.604186,21.601502
...,...,...,...,...,...,...
204,8in GT Luxe MF,4.137500,1279730.20,5.294884e+06,0.207826,89.008027
78,Jayanna BIFD 7.5in,4.631944,1114260.42,5.161192e+06,0.202578,89.210605
180,Joseph 14in,3.993056,1291219.06,5.155909e+06,0.202371,89.412976
265,6in Ultima Foam,2.267224,2273025.21,5.153457e+06,0.202275,89.615251
272,"Suzanne HB, Grey",4.327273,1190237.65,5.150483e+06,0.202158,89.817409