## WonderBox Only 분석 : 년평균 평점-매출 데이터 --> WonderBox 컬렉션 추출 --> Contribution --> 증감패턴

In [3]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [4]:
df = pd.read_csv('review-vc_sales-by_collection_category_20250429.csv')

In [9]:
df['collection'].nunique()

668

In [11]:
filtered_df = df[['yr', 'financial_category', 'collection', 'written_avg_rating', 'sales_amount']]
filtered_df = filtered_df.rename(columns={'financial_category':'category'})
#filtered_df = filtered_df.rename(columns={'coalesce_collection':'collection1'})
filtered_df = filtered_df.rename(columns={'written_avg_rating':'rating'})
filtered_df = filtered_df.rename(columns={'sales_amount':'sales'})

In [ ]:
filtered_df

In [20]:
#agg_df = filtered_df.groupby(['yr','category','collection1']).agg({
#    'rating': 'mean',
#    'sales': 'sum'
#}).reset_index()

In [38]:
df_map = pd.read_csv('wonderbox_collection_mapping.csv')

In [42]:
df_map.head(5)

  big_box_collection small_box_collection
0            Shalini    WonderBox Shalini
1           Dachelle   WonderBox Dachelle
2             Curtis     WonderBox Curtis
3             Kellen     WonderBox Kellen
4               Judy       WonderBox Judy

In [48]:
big_box_list = df_map['big_box_collection'].tolist()
small_box_list = df_map['small_box_collection'].tolist()

In [64]:
df_big = filtered_df[filtered_df['collection'].isin(big_box_list)].copy()
df_small = filtered_df[filtered_df['collection'].isin(small_box_list)].copy()

In [ ]:
df_small#['category'].unique()

In [72]:
df_big['box_type'] = 'big_box'
df_small['box_type'] = 'small_box'

In [74]:
df_wonderbox = pd.concat([df_big, df_small], ignore_index=True)

In [76]:
df_wonderbox

,yr,category,collection,rating,sales,box_type
0,2022,Box Springs,Edgar 4in,4.568966,976224.39,big_box
1,2022,Box Springs,Edgar 8in,3.954545,812443.93,big_box
2,2022,Platform Beds,Lorelai 14in,3.886410,6593250.92,big_box
3,2022,Platform Beds,Van 16in,3.711244,14026986.71,big_box
4,2022,Platform Beds,Joseph 14in,3.838235,1291219.06,big_box
...,...,...,...,...,...,...
166,2025,Toppers,3in GTFT w WonderBox,5.000000,49908.21,small_box
167,2025,Toppers,2in SWFT w WonderBox,4.000000,35974.81,small_box
168,2025,Toppers,2in MGT w WonderBox,1.000000,19037.86,small_box
169,2025,Toppers,1.5in SWFT w WonderBox,3.400000,75473.95,small_box
170,2025,Toppers,1.5in GTFT w WonderBox,2.000000,27383.58,small_box

In [78]:
# yr 값을 컬럼으로 변환 (pivot)
pivot_df = df_wonderbox.pivot_table(index=['category','collection','box_type'],
                              columns='yr',
                              values=['rating','sales'])

In [80]:
# 컬럼 이름을 정리 (multi-index 해제)
#pivot_df.columns = [f"{val}_{yr}" for val, yr in pivot_df.columns]
pivot_df.columns = [f"{yr}_{val}" for val, yr in pivot_df.columns]

In [82]:
pivot_df

                                                2022_rating  2023_rating  \
category      collection             box_type
Box Springs   Edgar 4in              big_box       4.568966     4.592593
              Edgar 8in              big_box       3.954545     4.653846
              Edgar Bamboo 4in       small_box          NaN          NaN
              Edgar Bamboo 8in       small_box          NaN          NaN
Platform Beds Abel                   big_box       4.009821     3.930267
              Curtis                 big_box       4.169761     3.933921
              Dachelle               big_box       4.630081     4.643519
              Ibidun                 big_box       4.095238          NaN
              Joseph 10in            big_box       4.100629     4.136364
              Joseph 14in            big_box       3.838235     3.571429
              Joseph 18in            big_box       3.482270     2.623188
              Joseph 6in             big_box       4.380282     3.722222
              Judy                   big_box       4.680328     4.487805
              Kellen                 big_box       4.554054     4.708333
              Lorelai 14in           big_box       3.886410     3.643145
              Shalini                big_box       4.290756     4.262087
              Van 16in               big_box       3.711244     3.450820
              WonderBox Abel         small_box          NaN          NaN
              WonderBox Curtis       small_box          NaN          NaN
              WonderBox Dachelle     small_box          NaN          NaN
              WonderBox Ibidun       small_box          NaN          NaN
              WonderBox Joseph 10in  small_box          NaN          NaN
              WonderBox Joseph 14in  small_box          NaN          NaN
              WonderBox Joseph 18in  small_box          NaN          NaN
              WonderBox Joseph 6in   small_box          NaN          NaN
              WonderBox Judy         small_box          NaN          NaN
              WonderBox Kellen       small_box          NaN          NaN
              WonderBox Lorelai 14in small_box          NaN          NaN
              WonderBox Shalini      small_box          NaN          NaN
              WonderBox Van 16in     small_box          NaN          NaN
              WonderBox Yelena 14in  small_box          NaN          NaN
              WonderBox Yelena 18in  small_box          NaN          NaN
              Yelena 14in            big_box       3.856338     3.573034
              Yelena 18in            big_box       4.750000     4.055556
Toppers       1.5in GT MF            big_box       3.110000     3.115789
              1.5in GTFT w WonderBox small_box          NaN          NaN
              1.5in SWFT w WonderBox small_box          NaN          NaN
              1.5in Swirl Gel        big_box       2.518201     2.512712
              2in MGT w WonderBox    small_box          NaN          NaN
              2in MyGel              big_box       3.818182     3.625000
              2in SWFT w WonderBox   small_box          NaN          NaN
              2in Swirl Gel          big_box       2.090395     2.434524
              3in GT MF              big_box       3.755102     3.835165
              3in GTFT w WonderBox   small_box          NaN          NaN
              3in MGT w WonderBox    small_box          NaN          NaN
              3in MyGel              big_box       3.333333     3.650000
              3in SWFT w WonderBox   small_box          NaN     2.000000
              3in Swirl Gel          big_box       2.326848     2.044444
              4in GT MF              big_box       3.457627     3.628049
              4in GTFT w WonderBox   small_box          NaN          NaN
              4in MGT w WonderBox    small_box          NaN          NaN
              4in MyGel              big_box       4.075472     3.482759
              4in SWFT w WonderBox   small_box          NaN          NaN
              4in Swirl Gel          big_box       3.500000     3.666667

                                                2024_rating  2025_rating  \
category      collection             box_type
Box Springs   Edgar 4in              big_box       4.370370     5.000000
              Edgar 8in              big_box       3.666667     2.500000
              Edgar Bamboo 4in       small_box     4.400000     4.777778
              Edgar Bamboo 8in       small_box     3.800000     2.000000
Platform Beds Abel                   big_box       4.034632     4.025000
              Curtis                 big_box       3.407895     2.882353
              Dachelle               big_box       4.352113     5.000000
              Ibidun                 big_box       1.000000     5.000000
              Joseph 10in            big_box       3.909091     3.400000
              Joseph 14in            big_box       3.419355     2.000000
              Joseph 18in            big_box       2.518519     1.500000
              Joseph 6in             big_box       3.916667     3.500000
              Judy                   big_box       4.390244     3.666667
              Kellen                 big_box       5.000000     5.000000
              Lorelai 14in           big_box       4.105469     3.833333
              Shalini                big_box       4.148148     4.608696
              Van 16in               big_box       3.681499     3.285714
              WonderBox Abel         small_box     2.250000     3.750000
              WonderBox Curtis       small_box     3.200000     3.666667
              WonderBox Dachelle     small_box     3.111111     3.428571
              WonderBox Ibidun       small_box     4.000000     4.000000
              WonderBox Joseph 10in  small_box     5.000000     5.000000
              WonderBox Joseph 14in  small_box     3.000000     2.500000
              WonderBox Joseph 18in  small_box     3.375000     5.000000
              WonderBox Joseph 6in   small_box     2.400000     3.500000
              WonderBox Judy         small_box     4.000000     1.500000
              WonderBox Kellen       small_box          NaN          NaN
              WonderBox Lorelai 14in small_box     2.920000     2.400000
              WonderBox Shalini      small_box     3.500000     3.000000
              WonderBox Van 16in     small_box     3.071429     3.214286
              WonderBox Yelena 14in  small_box     2.200000     1.000000
              WonderBox Yelena 18in  small_box     1.000000     4.666667
              Yelena 14in            big_box       3.775281     3.375000
              Yelena 18in            big_box       4.454545          NaN
Toppers       1.5in GT MF            big_box       3.526316     2.000000
              1.5in GTFT w WonderBox small_box     3.666667     2.000000
              1.5in SWFT w WonderBox small_box     3.529412     3.400000
              1.5in Swirl Gel        big_box       2.629310     3.000000
              2in MGT w WonderBox    small_box     3.000000     1.000000
              2in MyGel              big_box       3.750000     1.000000
              2in SWFT w WonderBox   small_box     3.375000     4.000000
              2in Swirl Gel          big_box       3.857143     2.000000
              3in GT MF              big_box       4.280000     4.000000
              3in GTFT w WonderBox   small_box     3.800000     5.000000
              3in MGT w WonderBox    small_box     4.000000     4.000000
              3in MyGel              big_box       3.400000     3.500000
              3in SWFT w WonderBox   small_box     4.285714     4.000000
              3in Swirl Gel          big_box       2.487805     2.250000
              4in GT MF              big_box       3.487805     3.000000
              4in GTFT w WonderBox   small_box     3.577778     2.105263
              4in MGT w WonderBox    small_box     4.000000     4.200000
              4in MyGel              big_box       3.083333     3.500000
              4in SWFT w WonderBox   small_box     3.000000     1.333333
              4in Swirl Gel          big_box       4.600000          NaN

                                                 2022_sales  2023_sales  \
category      collection             box_type
Box Springs   Edgar 4in              big_box      976224.39   861552.85
              Edgar 8in              big_box      812443.93   522479.81
              Edgar Bamboo 4in       small_box          NaN         NaN
              Edgar Bamboo 8in       small_box          NaN         NaN
Platform Beds Abel                   big_box    14885563.48  7418001.00
              Curtis                 big_box     4944126.99  2279716.31
              Dachelle               big_box     6058234.47  4432053.86
              Ibidun                 big_box      558766.44   291703.14
              Joseph 10in            big_box     2564000.18  1059385.63
              Joseph 14in            big_box     1291219.06   491938.04
              Joseph 18in            big_box     1330709.97   547653.68
              Joseph 6in             big_box     2250515.77   992578.93
              Judy                   big_box     2249852.55  1494212.76
              Kellen                 big_box     1000720.08   352167.81
              Lorelai 14in           big_box     6593250.92  5523919.85
              Shalini                big_box    13958740.56  6833539.11
              Van 16in               big_box    14026986.71  4778613.50
              WonderBox Abel         small_box          NaN         NaN
              WonderBox Curtis       small_box          NaN         NaN
              WonderBox Dachelle     small_box          NaN         NaN
              WonderBox Ibidun       small_box          NaN         NaN
              WonderBox Joseph 10in  small_box          NaN         NaN
              WonderBox Joseph 14in  small_box          NaN         NaN
              WonderBox Joseph 18in  small_box          NaN         NaN
              WonderBox Joseph 6in   small_box          NaN         NaN
              WonderBox Judy         small_box          NaN         NaN
              WonderBox Kellen       small_box          NaN         NaN
              WonderBox Lorelai 14in small_box          NaN         NaN
              WonderBox Shalini      small_box          NaN         NaN
              WonderBox Van 16in     small_box          NaN         NaN
              WonderBox Yelena 14in  small_box          NaN         NaN
              WonderBox Yelena 18in  small_box          NaN         NaN
              Yelena 14in            big_box     4370093.56  2765322.53
              Yelena 18in            big_box      295669.90   358245.50
Toppers       1.5in GT MF            big_box      420682.77   459797.33
              1.5in GTFT w WonderBox small_box          NaN      322.15
              1.5in SWFT w WonderBox small_box          NaN     2520.30
              1.5in Swirl Gel        big_box     2179586.61  1193168.69
              2in MGT w WonderBox    small_box          NaN     1266.42
              2in MyGel              big_box      201560.98   187047.33
              2in SWFT w WonderBox   small_box          NaN     1577.05
              2in Swirl Gel          big_box     1557398.36   632210.74
              3in GT MF              big_box      593356.51   702004.01
              3in GTFT w WonderBox   small_box          NaN      710.40
              3in MGT w WonderBox    small_box          NaN      462.22
              3in MyGel              big_box      198521.66   153763.85
              3in SWFT w WonderBox   small_box          NaN     2386.82
              3in Swirl Gel          big_box     1063852.87   672699.75
              4in GT MF              big_box     1113506.27  1325976.26
              4in GTFT w WonderBox   small_box          NaN      204.81
              4in MGT w WonderBox    small_box          NaN        0.00
              4in MyGel              big_box      436691.26   292672.49
              4in SWFT w WonderBox   small_box          NaN         NaN
              4in Swirl Gel          big_box      269305.47   153721.07

                                                2024_sales  2025_sales
category      collection             box_type
Box Springs   Edgar 4in              big_box     249847.22    33978.00
              Edgar 8in              big_box     154282.00     9294.58
              Edgar Bamboo 4in       small_box   245216.48   148089.20
              Edgar Bamboo 8in       small_box   138660.84    68403.46
Platform Beds Abel                   big_box    2309102.92   242229.27
              Curtis                 big_box     659478.50    85085.31
              Dachelle               big_box    1044977.00    38816.72
              Ibidun                 big_box     123749.60     8242.29
              Joseph 10in            big_box     347580.50    34739.69
              Joseph 14in            big_box     186966.22    29118.64
              Joseph 18in            big_box     125684.35     7412.63
              Joseph 6in             big_box     242220.34    32314.67
              Judy                   big_box     521056.26    31282.98
              Kellen                 big_box      59217.33     8220.46
              Lorelai 14in           big_box    2144231.05    73315.80
              Shalini                big_box    1902487.32   147364.13
              Van 16in               big_box    4350481.32   164847.22
              WonderBox Abel         small_box   161699.83    41540.52
              WonderBox Curtis       small_box   278911.38    62103.72
              WonderBox Dachelle     small_box   218857.30    86222.90
              WonderBox Ibidun       small_box    21342.99    21436.97
              WonderBox Joseph 10in  small_box    95488.72    14391.60
              WonderBox Joseph 14in  small_box    43941.40     5174.56
              WonderBox Joseph 18in  small_box    39504.21     8272.76
              WonderBox Joseph 6in   small_box    64187.89    18551.18
              WonderBox Judy         small_box    65739.75    47562.43
              WonderBox Kellen       small_box        0.00    11432.45
              WonderBox Lorelai 14in small_box   359645.23    87745.13
              WonderBox Shalini      small_box   360598.97   174166.54
              WonderBox Van 16in     small_box   348693.84    48127.08
              WonderBox Yelena 14in  small_box   113745.81    27195.18
              WonderBox Yelena 18in  small_box    62294.80    23949.97
              Yelena 14in            big_box     655762.89    34677.65
              Yelena 18in            big_box     116629.02        0.00
Toppers       1.5in GT MF            big_box     119591.83    10283.62
              1.5in GTFT w WonderBox small_box    41520.80    27383.58
              1.5in SWFT w WonderBox small_box   160930.01    75473.95
              1.5in Swirl Gel        big_box     413831.36    14004.30
              2in MGT w WonderBox    small_box    64787.20    19037.86
              2in MyGel              big_box      64144.20    13499.49
              2in SWFT w WonderBox   small_box   165981.45    35974.81
              2in Swirl Gel          big_box     125107.31     3969.54
              3in GT MF              big_box     179783.05    29617.54
              3in GTFT w WonderBox   small_box   383197.46    49908.21
              3in MGT w WonderBox    small_box   108641.97    18015.59
              3in MyGel              big_box      61810.98     4738.51
              3in SWFT w WonderBox   small_box   123232.16    20201.96
              3in Swirl Gel          big_box     102440.92     4880.85
              4in GT MF              big_box     183071.00     3487.65
              4in GTFT w WonderBox   small_box   671017.31   171566.86
              4in MGT w WonderBox    small_box    82338.03    27936.48
              4in MyGel              big_box     120875.88     5573.18
              4in SWFT w WonderBox   small_box   154761.26    33740.54
              4in Swirl Gel          big_box      19604.73         NaN

In [84]:
pivot_df.reset_index()
pivot_df.to_csv('review_sales_wonderbox_only_out_02.csv')

## 증감 패턴 구하기

In [86]:
df = pd.read_csv('review_sales_wonderbox_only_out_02.csv')

In [90]:
df.head(3)

,category,collection,box_type,2022_rating,2023_rating,2024_rating,2025_rating,2022_sales,2023_sales,2024_sales,2025_sales
0,Box Springs,Edgar 4in,big_box,4.568966,4.592593,4.370370,5.000000,976224.39,861552.85,249847.22,33978.00
1,Box Springs,Edgar 8in,big_box,3.954545,4.653846,3.666667,2.500000,812443.93,522479.81,154282.00,9294.58
2,Box Springs,Edgar Bamboo 4in,small_box,NaN,NaN,4.400000,4.777778,NaN,NaN,245216.48,148089.20

In [92]:
df['2022_weight'] = df['2022_rating'] * df['2022_sales']
df['2023_weight'] = df['2023_rating'] * df['2023_sales']
df['2024_weight'] = df['2024_rating'] * df['2024_sales']
df['2025_weight'] = df['2025_rating'] * df['2025_sales']

In [94]:
y2022_total_weight = df['2022_weight'].sum()
df['2022_contribution'] = df['2022_weight']/y2022_total_weight

y2023_total_weight = df['2023_weight'].sum()
df['2023_contribution'] = df['2023_weight']/y2023_total_weight

y2024_total_weight = df['2024_weight'].sum()
df['2024_contribution'] = df['2024_weight']/y2024_total_weight

y2025_total_weight = df['2025_weight'].sum()
df['2025_contribution'] = df['2025_weight']/y2025_total_weight

In [96]:
df.head(5)

,category,collection,box_type,2022_rating,2023_rating,2024_rating,2025_rating,2022_sales,2023_sales,2024_sales,2025_sales,2022_weight,2023_weight,2024_weight,2025_weight,2022_contribution,2023_contribution,2024_contribution,2025_contribution
0,Box Springs,Edgar 4in,big_box,4.568966,4.592593,4.370370,5.000000,976224.39,861552.85,249847.22,33978.00,4.460336e+06,3.956761e+06,1.091925e+06,169890.000000,0.013044,0.022046,0.013720,0.020512
1,Box Springs,Edgar 8in,big_box,3.954545,4.653846,3.666667,2.500000,812443.93,522479.81,154282.00,9294.58,3.212846e+06,2.431541e+06,5.657007e+05,23236.450000,0.009395,0.013548,0.007108,0.002805
2,Box Springs,Edgar Bamboo 4in,small_box,NaN,NaN,4.400000,4.777778,NaN,NaN,245216.48,148089.20,NaN,NaN,1.078953e+06,707537.288922,NaN,NaN,0.013557,0.085424
3,Box Springs,Edgar Bamboo 8in,small_box,NaN,NaN,3.800000,2.000000,NaN,NaN,138660.84,68403.46,NaN,NaN,5.269112e+05,136806.920000,NaN,NaN,0.006621,0.016517
4,Platform Beds,Abel,big_box,4.009821,3.930267,4.034632,4.025000,14885563.48,7418001.00,2309102.92,242229.27,5.968845e+07,2.915472e+07,9.316381e+06,974972.811750,0.174550,0.162445,0.117059,0.117713

## Rating, Contribution 증감 패턴 구하기

In [98]:
# 1. rating_slope 컬럼 추가: 결측치 제외 후 연간 rating으로 기울기 계산
def calc_rating_slope(row):
    ratings = [row['2022_rating'], row['2023_rating'], row['2024_rating'], row['2025_rating']]
    years = [2022, 2023, 2024, 2025]

    # 결측치 아닌 값만 골라내기
    valid_x = []
    valid_y = []

    for i, r in enumerate(ratings):
        if pd.notna(r): 
            valid_x.append(i)
            valid_y.append(r)

    if len(valid_x) <= 1:
        return 0

    x = np.array(valid_x).reshape(-1,1)
    y = np.array(valid_y)

    model = LinearRegression()
    model.fit(x,y)
    return model.coef_[0]

In [100]:
df['rating_slope'] = df.apply(calc_rating_slope, axis=1)

In [102]:
def determine_trend(slope):
    if slope > 0: 
        return 1
    elif slope < 0:
        return -1
    else: 
        return 0

In [104]:
df['rating_trend'] = df['rating_slope'].apply(determine_trend)

In [108]:
df.head(3)
#df[df['collection1'].str.contains('Armita')]

,category,collection,box_type,2022_rating,2023_rating,2024_rating,2025_rating,2022_sales,2023_sales,2024_sales,...,2022_weight,2023_weight,2024_weight,2025_weight,2022_contribution,2023_contribution,2024_contribution,2025_contribution,rating_slope,rating_trend
0,Box Springs,Edgar 4in,big_box,4.568966,4.592593,4.370370,5.000000,976224.39,861552.85,249847.22,...,4.460336e+06,3.956761e+06,1.091925e+06,169890.000000,0.013044,0.022046,0.013720,0.020512,0.107088,1
1,Box Springs,Edgar 8in,big_box,3.954545,4.653846,3.666667,2.500000,812443.93,522479.81,154282.00,...,3.212846e+06,2.431541e+06,5.657007e+05,23236.450000,0.009395,0.013548,0.007108,0.002805,-0.535082,-1
2,Box Springs,Edgar Bamboo 4in,small_box,NaN,NaN,4.400000,4.777778,NaN,NaN,245216.48,...,NaN,NaN,1.078953e+06,707537.288922,NaN,NaN,0.013557,0.085424,0.377778,1

In [110]:
# 2. contribution_slope 컬럼 추가: 결측치 제외 후 연간 contribution 기울기 계산
def calc_contribution_slope(row):
    contributions = [row['2022_contribution'], row['2023_contribution'], row['2024_contribution'], row['2025_contribution']]
    years = [2022, 2023, 2024, 2025]

    # 결측치 아닌 값만 골라내기
    valid_x = []
    valid_y = []

    for i, r in enumerate(contributions):
        if pd.notna(r): 
            valid_x.append(i)
            valid_y.append(r)

    if len(valid_x) <= 1:
        return 0

    x = np.array(valid_x).reshape(-1,1)
    y = np.array(valid_y)

    model = LinearRegression()
    model.fit(x,y)
    return model.coef_[0]

In [112]:
df['contribution_slope'] = df.apply(calc_contribution_slope, axis=1)

In [114]:
df['contribution_trend'] = df['contribution_slope'].apply(determine_trend)

In [116]:
df.head(5)

,category,collection,box_type,2022_rating,2023_rating,2024_rating,2025_rating,2022_sales,2023_sales,2024_sales,...,2024_weight,2025_weight,2022_contribution,2023_contribution,2024_contribution,2025_contribution,rating_slope,rating_trend,contribution_slope,contribution_trend
0,Box Springs,Edgar 4in,big_box,4.568966,4.592593,4.370370,5.000000,976224.39,861552.85,249847.22,...,1.091925e+06,169890.000000,0.013044,0.022046,0.013720,0.020512,0.107088,1,0.001408,1
1,Box Springs,Edgar 8in,big_box,3.954545,4.653846,3.666667,2.500000,812443.93,522479.81,154282.00,...,5.657007e+05,23236.450000,0.009395,0.013548,0.007108,0.002805,-0.535082,-1,-0.002621,-1
2,Box Springs,Edgar Bamboo 4in,small_box,NaN,NaN,4.400000,4.777778,NaN,NaN,245216.48,...,1.078953e+06,707537.288922,NaN,NaN,0.013557,0.085424,0.377778,1,0.071867,1
3,Box Springs,Edgar Bamboo 8in,small_box,NaN,NaN,3.800000,2.000000,NaN,NaN,138660.84,...,5.269112e+05,136806.920000,NaN,NaN,0.006621,0.016517,-1.800000,-1,0.009897,1
4,Platform Beds,Abel,big_box,4.009821,3.930267,4.034632,4.025000,14885563.48,7418001.00,2309102.92,...,9.316381e+06,974972.811750,0.174550,0.162445,0.117059,0.117713,0.014990,1,-0.021590,-1

In [118]:
df.to_csv('review_sales_wonderbox_only_pattern_out_01.csv')